// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type ContainerRenameReq struct {
	IdReq
	NewName string `form:"newName"`
}

type ContainerRestoreReq struct {
	Filename string `json:"filename"`
}

type ContainerUpdateReq struct {
	IdReq
	ImageNameAndTag string `form:"imageNameAndTag"`
	ContainerName   string `form:"containerName"`
}

type CreateContainerReq struct {
	OldName         string `json:"old_name"`
	NewName         string `json:"new_name"`
	ImageNameAndTag string `json:"image_name_and_tag"`
}

type DelContainerBackupReq struct {
	Filename string `form:"filename"`
}

type DoLoginReq struct {
	SecretKey string `form:"secret_key,optional"`
}

type GetProgressReq struct {
	TaskId string `path:"taskid"`
}

type IdReq struct {
	Id string `path:"id"`
	// HostID 容器所属 Docker 主机（多 Docker 管理），空表示本地。
	HostID string `form:"hostId,optional"`
}

type LoginReq struct {
	SecretKey string `form:"secretKey,optional"`
}

type MsgResp struct {
	Status string `json:"status"`
	Msg    string `json:"msg"`
}

type RemoveContainerReq struct {
	Name string `json:"name"`
}

type RemoveImageReq struct {
	IdReq
	Force bool `form:"force,default=false"`
}

// PruneImagesReq 批量清理镜像请求：提交镜像ID列表，异步逐个删除。
type PruneImagesReq struct {
	Ids   []string `json:"ids"`
	Force bool     `json:"force,default=false"`
}

type RenameContainerReq struct {
	OldName string `json:"oldName"`
	NewName string `json:"newName"`
}

type Resp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type StartContainerReq struct {
	Name string `json:"name"`
}

type StopContainerReq struct {
	Name string `json:"name"`
}

type VerifyJwtReq struct {
	Jwt string `form:"jwt,optional"`
}

type VersionMsgResp struct {
	Version   string `json:"version"`
	BuildDate string `json:"build_date"`
}

type VersionReq struct {
	Type string `form:"type"`
}

type GetNewImageReq struct {
	ImageNameAndTag string `json:"image_name_and_tag"`
}

// HostPathResolveReq 解析容器路径到宿主机路径请求。
type HostPathResolveReq struct {
	ContainerPath string `json:"containerPath"`
}

// HostPathConfigReq 保存宿主机路径映射配置请求。
type HostPathConfigReq struct {
	Enabled  bool                  `json:"enabled"`
	Mode     string                `json:"mode"` // auto | custom
	Mappings []HostPathMappingItem `json:"mappings"`
}

// HostPathMappingItem 自定义模式下的单条映射。
type HostPathMappingItem struct {
	ContainerPath string `json:"containerPath"`
	HostPath      string `json:"hostPath"`
}

// DockerHostReq 多 Docker 主机的创建/更新请求。
// ID 为空表示新建；非空表示更新。本地主机（id=local）仅允许改名，地址/类型固定。
type DockerHostReq struct {
	ID      string `json:"id,optional"`
	Name    string `json:"name"`
	Address string `json:"address,optional"` // 远程形如 tcp://ip:2375；本地忽略此字段
	Enabled bool   `json:"enabled,optional"`
	Note    string `json:"note,optional"`
}

// DockerHostIDReq 按 ID 操作 Docker 主机（删除、连通性测试）。
type DockerHostIDReq struct {
	ID string `path:"id"`
}
