// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	auth "github.com/l429609201/dockerCopilot/internal/handler/auth"
	bot "github.com/l429609201/dockerCopilot/internal/handler/bot"
	compose "github.com/l429609201/dockerCopilot/internal/handler/compose"
	container "github.com/l429609201/dockerCopilot/internal/handler/container"
	favicon "github.com/l429609201/dockerCopilot/internal/handler/favicon"
	icons "github.com/l429609201/dockerCopilot/internal/handler/icons"
	image "github.com/l429609201/dockerCopilot/internal/handler/image"
	ops "github.com/l429609201/dockerCopilot/internal/handler/ops"
	progress "github.com/l429609201/dockerCopilot/internal/handler/progress"
	schedule "github.com/l429609201/dockerCopilot/internal/handler/schedule"
	version "github.com/l429609201/dockerCopilot/internal/handler/version"
	"github.com/l429609201/dockerCopilot/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: webindexHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth",
				Handler: auth.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/rename",
				Handler: container.RenameHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/restart",
				Handler: container.RestartHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/start",
				Handler: container.StartHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/stop",
				Handler: container.StopHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/update",
				Handler: container.UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/backup",
				Handler: container.BackupHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/backup2compose",
				Handler: container.Backup2composeHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/container/backups",
				Handler: container.DelRestoreHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/backups/restore",
				Handler: container.RestoreHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/listBackups",
				Handler: container.ListBackupsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/containers",
				Handler: container.ContainersListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: icons.UploadHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: icons.ObtainHandler(serverCtx),
			},
			{
				// 通过图标 URL 绑定到镜像名（无需上传图片）
				Method:  http.MethodPost,
				Path:    "/url",
				Handler: icons.SetIconURLHandler(serverCtx),
			},
			{
				// 自动抓取站点 favicon 并下载持久化到 /data/images，绑定镜像名
				Method:  http.MethodPost,
				Path:    "/fetch",
				Handler: icons.FetchIconHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/icons"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodDelete,
				Path:    "/image/:id",
				Handler: image.RemoveHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/images",
				Handler: image.ImagesListHandler(serverCtx),
			},
			{
				// 异步批量清理镜像：提交即返回 taskID，进度经 /api/progress/:taskid 查询
				Method:  http.MethodPost,
				Path:    "/images/prune",
				Handler: image.PruneHandler(serverCtx),
			},
			{
				// 手动触发检测所有镜像更新（异步执行，立即返回）
				Method:  http.MethodPost,
				Path:    "/images/check-update",
				Handler: image.CheckUpdateHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/progress/:taskid",
				Handler: progress.GetProgressHandler(serverCtx),
			},
			{
				// 取消正在执行的任务（拉取等可中断阶段生效）
				Method:  http.MethodPost,
				Path:    "/progress/:taskid/cancel",
				Handler: progress.CancelProgressHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/program",
				Handler: version.UpdateProgramHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/version",
				Handler: version.VersionHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	// 定时更新规则管理
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/schedules",
				Handler: schedule.ListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/schedules",
				Handler: schedule.SaveHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/schedules/:id",
				Handler: schedule.DeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/schedules/:id/run",
				Handler: schedule.RunNowHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	// Registry 凭据管理
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/registries",
				Handler: schedule.RegistryListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/registries",
				Handler: schedule.RegistrySaveHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/registries/:id",
				Handler: schedule.RegistryDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/registries/:id/ratelimit",
				Handler: schedule.RegistryRateLimitHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	// Compose 项目管理
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/compose/projects",
				Handler: compose.ListHandler(serverCtx),
			},
			{
				// 读取 Compose 扫描配置（供前端配置卡片回显）
				Method:  http.MethodGet,
				Path:    "/compose/config",
				Handler: compose.GetConfigHandler(serverCtx),
			},
			{
				// 保存 Compose 扫描配置（写入持久化存储，即时生效）
				Method:  http.MethodPut,
				Path:    "/compose/config",
				Handler: compose.SaveConfigHandler(serverCtx),
			},
			{
				// 浏览 DC 自身文件系统目录（目录选择器用，只读，返回子目录和文件列表）
				Method:  http.MethodGet,
				Path:    "/compose/browse",
				Handler: compose.BrowseHandler(serverCtx),
			},
			{
				// 在指定目录下创建文件夹
				Method:  http.MethodPost,
				Path:    "/compose/folder",
				Handler: compose.CreateFolderHandler(serverCtx),
			},
			{
				// 在指定目录下创建 Compose 配置文件
				Method:  http.MethodPost,
				Path:    "/compose/file",
				Handler: compose.CreateComposeFileHandler(serverCtx),
			},
			{
				// 读取任意文件内容（文件管理器用）
				Method:  http.MethodGet,
				Path:    "/files",
				Handler: compose.ReadFileByPathHandler(serverCtx),
			},
			{
				// 保存文件内容（文件管理器用）
				Method:  http.MethodPut,
				Path:    "/files",
				Handler: compose.SaveFileByPathHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/compose/validate",
				Handler: compose.ValidateHandler(serverCtx),
			},
			{
				// 从内容创建并部署一个新的 Compose 项目（写入工作目录后 up）
				Method:  http.MethodPost,
				Path:    "/compose/create",
				Handler: compose.CreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/compose/projects/:id/files/:filename",
				Handler: compose.ReadFileHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/compose/projects/:id/files/:filename",
				Handler: compose.SaveFileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/compose/projects/:id/action",
				Handler: compose.ActionHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	// 宿主机路径映射
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取宿主机路径映射配置（含自动推导预览）
				Method:  http.MethodGet,
				Path:    "/hostpath/config",
				Handler: ops.HostPathConfigGetHandler(serverCtx),
			},
			{
				// 保存宿主机路径映射配置
				Method:  http.MethodPost,
				Path:    "/hostpath/config",
				Handler: ops.HostPathConfigSaveHandler(serverCtx),
			},
			{
				// 解析容器路径到宿主机路径并校验可访问性
				Method:  http.MethodPost,
				Path:    "/hostpath/resolve",
				Handler: ops.HostPathResolveHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	// 多 Docker 主机管理
	server.AddRoutes(
		[]rest.Route{
			{
				// 列出全部 Docker 主机及在线状态
				Method:  http.MethodGet,
				Path:    "/docker/hosts",
				Handler: ops.DockerHostListHandler(serverCtx),
			},
			{
				// 新建或更新 Docker 主机
				Method:  http.MethodPost,
				Path:    "/docker/hosts",
				Handler: ops.DockerHostSaveHandler(serverCtx),
			},
			{
				// 删除远程 Docker 主机
				Method:  http.MethodDelete,
				Path:    "/docker/hosts/:id",
				Handler: ops.DockerHostDeleteHandler(serverCtx),
			},
			{
				// 测试指定 Docker 主机连通性
				Method:  http.MethodPost,
				Path:    "/docker/hosts/:id/ping",
				Handler: ops.DockerHostPingHandler(serverCtx),
			},
			{
				// 获取指定 Docker 主机的详细信息（docker info + version）
				Method:  http.MethodGet,
				Path:    "/docker/hosts/:id/info",
				Handler: ops.DockerHostInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	// Telegram Bot 配置
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/bot/telegram",
				Handler: bot.GetConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/bot/telegram",
				Handler: bot.SaveConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/bot/telegram/test",
				Handler: bot.TestConfigHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	// 阶段7：Portainer 风格容器运维（生命周期、日志、命令、详情）
	server.AddRoutes(
		[]rest.Route{
			{
				// 从零创建新容器（镜像/端口/环境变量/卷/网络/重启策略），支持多 Docker 主机
				Method:  http.MethodPost,
				Path:    "/container/create",
				Handler: ops.CreateContainerHandler(serverCtx),
			},
			{
				// 解析 docker run 命令为创建参数（仅解析预览，不创建）
				Method:  http.MethodPost,
				Path:    "/container/parseRunCommand",
				Handler: ops.ParseRunCommandHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/pause",
				Handler: ops.PauseHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/unpause",
				Handler: ops.UnpauseHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/kill",
				Handler: ops.KillHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/container/:id",
				Handler: ops.RemoveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/rename2",
				Handler: ops.RenameHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/:id/inspect",
				Handler: ops.InspectHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/:id/logs",
				Handler: ops.LogsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/exec",
				Handler: ops.ExecHandler(serverCtx),
			},
			{
				// 获取容器进程列表（docker top）
				Method:  http.MethodGet,
				Path:    "/container/:id/top",
				Handler: ops.TopHandler(serverCtx),
			},
			{
				// 参数编辑（任务化重建），返回 taskID
				Method:  http.MethodPut,
				Path:    "/container/:id/edit",
				Handler: ops.EditHandler(serverCtx),
			},
			// ===== 容器文件管理（路径穿越已在服务层统一校验）=====
			{
				Method:  http.MethodGet,
				Path:    "/container/:id/files",
				Handler: ops.FileListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/:id/files/read",
				Handler: ops.FileReadHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/:id/files/download",
				Handler: ops.FileDownloadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/files/upload",
				Handler: ops.FileUploadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/files/write",
				Handler: ops.FileWriteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/files/mkdir",
				Handler: ops.FileMkdirHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/files/delete",
				Handler: ops.FileDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/files/rename",
				Handler: ops.FileRenameHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	// 阶段8：favicon 解析（供前端按容器端口抓取站点图标）
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/favicon/resolve",
				Handler: favicon.ResolveHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	// 阶段9：容器交互式终端（WebSocket）。
	// 不走 WithJwt 中间件（浏览器 WebSocket 无法自定义 Authorization 头），
	// 改由 handler 内校验 query 中的 token。
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/container/:id/exec/ws",
				Handler: ops.ExecWSHandler(serverCtx),
			},
			{
				// 容器资源监控 SSE 推送（EventSource 无法带 Authorization 头，用 query token）
				Method:  http.MethodGet,
				Path:    "/container/stats/stream",
				Handler: ops.StatsStreamHandler(serverCtx),
			},
			{
				// 全部后台任务列表 SSE 推送（供任务中心实时展示所有任务）
				Method:  http.MethodGet,
				Path:    "/progress/stream",
				Handler: ops.ProgressStreamHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
