// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	auth "github.com/l429609201/dockerCopilot/internal/handler/auth"
	bot "github.com/l429609201/dockerCopilot/internal/handler/bot"
	compose "github.com/l429609201/dockerCopilot/internal/handler/compose"
	container "github.com/l429609201/dockerCopilot/internal/handler/container"
	favicon "github.com/l429609201/dockerCopilot/internal/handler/favicon"
	icons "github.com/l429609201/dockerCopilot/internal/handler/icons"
	image "github.com/l429609201/dockerCopilot/internal/handler/image"
	ops "github.com/l429609201/dockerCopilot/internal/handler/ops"
	progress "github.com/l429609201/dockerCopilot/internal/handler/progress"
	schedule "github.com/l429609201/dockerCopilot/internal/handler/schedule"
	version "github.com/l429609201/dockerCopilot/internal/handler/version"
	"github.com/l429609201/dockerCopilot/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: webindexHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth",
				Handler: auth.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/rename",
				Handler: container.RenameHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/restart",
				Handler: container.RestartHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/start",
				Handler: container.StartHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/stop",
				Handler: container.StopHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/update",
				Handler: container.UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/backup",
				Handler: container.BackupHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/backup2compose",
				Handler: container.Backup2composeHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/container/backups",
				Handler: container.DelRestoreHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/backups/restore",
				Handler: container.RestoreHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/listBackups",
				Handler: container.ListBackupsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/containers",
				Handler: container.ContainersListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: icons.UploadHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: icons.ObtainHandler(serverCtx),
			},
			{
				// 通过图标 URL 绑定到镜像名（无需上传图片）
				Method:  http.MethodPost,
				Path:    "/url",
				Handler: icons.SetIconURLHandler(serverCtx),
			},
			{
				// 自动抓取站点 favicon 并下载持久化到 /data/images，绑定镜像名
				Method:  http.MethodPost,
				Path:    "/fetch",
				Handler: icons.FetchIconHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/icons"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodDelete,
				Path:    "/image/:id",
				Handler: image.RemoveHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/images",
				Handler: image.ImagesListHandler(serverCtx),
			},
			{
				// 异步批量清理镜像：提交即返回 taskID，进度经 /api/progress/:taskid 查询
				Method:  http.MethodPost,
				Path:    "/images/prune",
				Handler: image.PruneHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/progress/:taskid",
				Handler: progress.GetProgressHandler(serverCtx),
			},
			{
				// 取消正在执行的任务（拉取等可中断阶段生效）
				Method:  http.MethodPost,
				Path:    "/progress/:taskid/cancel",
				Handler: progress.CancelProgressHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/program",
				Handler: version.UpdateProgramHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/version",
				Handler: version.VersionHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	// 定时更新规则管理
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/schedules",
				Handler: schedule.ListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/schedules/cron",
				Handler: schedule.GetCronHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/schedules/cron",
				Handler: schedule.SaveCronHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/schedules",
				Handler: schedule.SaveHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/schedules/:id",
				Handler: schedule.DeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/schedules/:id/run",
				Handler: schedule.RunNowHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	// Registry 凭据管理
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/registries",
				Handler: schedule.RegistryListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/registries",
				Handler: schedule.RegistrySaveHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/registries/:id",
				Handler: schedule.RegistryDeleteHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	// Compose 项目管理
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/compose/projects",
				Handler: compose.ListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/compose/validate",
				Handler: compose.ValidateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/compose/projects/:id/files/:filename",
				Handler: compose.ReadFileHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/compose/projects/:id/files/:filename",
				Handler: compose.SaveFileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/compose/projects/:id/action",
				Handler: compose.ActionHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	// Telegram Bot 配置
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/bot/telegram",
				Handler: bot.GetConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/bot/telegram",
				Handler: bot.SaveConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/bot/telegram/test",
				Handler: bot.TestConfigHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	// 阶段7：Portainer 风格容器运维（生命周期、日志、命令、详情）
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/pause",
				Handler: ops.PauseHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/unpause",
				Handler: ops.UnpauseHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/kill",
				Handler: ops.KillHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/container/:id",
				Handler: ops.RemoveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/rename2",
				Handler: ops.RenameHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/:id/inspect",
				Handler: ops.InspectHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/:id/logs",
				Handler: ops.LogsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/exec",
				Handler: ops.ExecHandler(serverCtx),
			},
			{
				// 参数编辑（任务化重建），返回 taskID
				Method:  http.MethodPut,
				Path:    "/container/:id/edit",
				Handler: ops.EditHandler(serverCtx),
			},
			// ===== 容器文件管理（路径穿越已在服务层统一校验）=====
			{
				Method:  http.MethodGet,
				Path:    "/container/:id/files",
				Handler: ops.FileListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/:id/files/read",
				Handler: ops.FileReadHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/:id/files/download",
				Handler: ops.FileDownloadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/files/upload",
				Handler: ops.FileUploadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/files/write",
				Handler: ops.FileWriteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/files/mkdir",
				Handler: ops.FileMkdirHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/files/delete",
				Handler: ops.FileDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/files/rename",
				Handler: ops.FileRenameHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	// 阶段8：favicon 解析（供前端按容器端口抓取站点图标）
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/favicon/resolve",
				Handler: favicon.ResolveHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	// 阶段9：容器交互式终端（WebSocket）。
	// 不走 WithJwt 中间件（浏览器 WebSocket 无法自定义 Authorization 头），
	// 改由 handler 内校验 query 中的 token。
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/container/:id/exec/ws",
				Handler: ops.ExecWSHandler(serverCtx),
			},
			{
				// 容器资源监控 SSE 推送（EventSource 无法带 Authorization 头，用 query token）
				Method:  http.MethodGet,
				Path:    "/container/stats/stream",
				Handler: ops.StatsStreamHandler(serverCtx),
			},
			{
				// 全部后台任务列表 SSE 推送（供任务中心实时展示所有任务）
				Method:  http.MethodGet,
				Path:    "/progress/stream",
				Handler: ops.ProgressStreamHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
